"""Vector store management for the Research Paper Answer Bot.

This module provides a persistent ChromaDB-backed vector store for storing
and retrieving document chunks using embeddings generated by the embedding
manager.
"""

import json
import logging
import uuid
from pathlib import Path
from typing import Any, Dict, List, Optional, cast

import chromadb
from langchain_chroma import Chroma
from langchain_core.documents import Document

from src.config import Config
from src.embeddings import EmbeddingError, EmbeddingManager


logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

if not logger.handlers:
    handler = logging.StreamHandler()
    formatter = logging.Formatter(
        "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    )
    handler.setFormatter(formatter)
    logger.addHandler(handler)


class VectorStoreError(Exception):
    """Raised when vector store operations fail."""


class VectorStoreManager:
    """Manage persistent ChromaDB storage for RAG document chunks."""

    def __init__(self, config: Config, embedding_manager: EmbeddingManager) -> None:
        """Initialize the vector store manager with configuration and embeddings."""
        self.config = config
        self.embedding_manager = embedding_manager
        self.collection_name = "research_papers"
        self.db_path = Path(config.chroma_db_path)
        self.db_path.mkdir(parents=True, exist_ok=True)

        self._client = chromadb.PersistentClient(path=str(self.db_path))
        self._collection = self._client.get_or_create_collection(name=self.collection_name)

        self._vectorstore: Optional[Any] = Chroma(
            client=self._client,
            collection_name=self.collection_name,
            embedding_function=self.embedding_manager.model,
            persist_directory=str(self.db_path),
        )
        logger.info("Vector store initialized at %s", self.db_path)

    def create_vector_store(self, documents: List[Document]) -> Any:
        """Create a fresh vector store from the provided document chunks."""
        if not documents:
            raise VectorStoreError("Cannot create vector store from an empty document list")

        if not all(isinstance(doc, Document) for doc in documents):
            raise VectorStoreError("All items must be langchain_core.documents.Document instances")

        try:
            self.reset_database()
            return self.add_documents(documents)
        except Exception as exc:
            raise VectorStoreError(f"Failed to create vector store: {exc}") from exc

    @staticmethod
    def _normalize_metadata_value(value: Any) -> Any:
        """Convert metadata values into Chroma-compatible scalar types."""
        if value is None or isinstance(value, (str, bool, int, float)):
            return value
        if isinstance(value, Path):
            return str(value)
        if isinstance(value, (list, tuple)):
            return [VectorStoreManager._normalize_metadata_value(item) for item in value]
        if isinstance(value, dict):
            return {str(key): VectorStoreManager._normalize_metadata_value(item) for key, item in value.items()}
        return str(value)

    @classmethod
    def _normalize_metadata(cls, metadata: Dict[str, Any]) -> Dict[str, Any]:
        """Normalize metadata keys and values for ChromaDB compatibility."""
        normalized: Dict[str, Any] = {}
        for key, value in metadata.items():
            normalized[str(key)] = cls._normalize_metadata_value(value)
            if isinstance(normalized[str(key)], (list, dict)):
                normalized[str(key)] = json.dumps(normalized[str(key)], ensure_ascii=False, default=str)
        return normalized

    def add_documents(self, documents: List[Document]) -> Any:
        """Store document chunks and embeddings into ChromaDB."""
        if not documents:
            raise VectorStoreError("Cannot add an empty document list")

        if not all(isinstance(doc, Document) for doc in documents):
            raise VectorStoreError("All items must be langchain_core.documents.Document instances")

        try:
            embedding_vectors = self.embedding_manager.create_embeddings(documents)
            normalized_embeddings: List[List[float]] = [
                [float(value) for value in embedding] for embedding in embedding_vectors
            ]
            texts = [doc.page_content for doc in documents]
            metadatas = [self._normalize_metadata(dict(doc.metadata)) for doc in documents]
            ids = [str(uuid.uuid4()) for _ in documents]

            self._collection.add(
                ids=ids,
                embeddings=cast(Any, normalized_embeddings),
                documents=texts,
                metadatas=cast(Any, metadatas),
            )

            self._vectorstore = Chroma(
                client=self._client,
                collection_name=self.collection_name,
                embedding_function=self.embedding_manager.model,
                persist_directory=str(self.db_path),
            )
            logger.info("Added %s document(s) to vector store", len(documents))
            return self._vectorstore
        except EmbeddingError as exc:
            raise VectorStoreError(f"Embedding failed: {exc}") from exc
        except Exception as exc:
            raise VectorStoreError(f"Failed to add documents to vector store: {exc}") from exc

    def similarity_search(self, query: str, k: int = 3) -> List[Document]:
        """Return the top-k relevant document chunks for a user query."""
        if not query or not query.strip():
            raise VectorStoreError("Query cannot be empty")

        if k <= 0:
            raise VectorStoreError("k must be greater than zero")

        try:
            query_embedding = self.embedding_manager.embed_query(query)
            results = self._collection.query(
                query_embeddings=[query_embedding],
                n_results=k,
            )

            documents: List[Document] = []
            if results.get("documents") and results["documents"]:
                raw_documents = results["documents"][0]
                raw_metadatas = results.get("metadatas") or []
                metadata_rows = raw_metadatas[0] if raw_metadatas and isinstance(raw_metadatas[0], list) else []

                for index, page_content in enumerate(raw_documents):
                    metadata = metadata_rows[index] if index < len(metadata_rows) else {}
                    documents.append(
                        Document(page_content=page_content, metadata=dict(metadata or {}))
                    )

            logger.info("Similarity search returned %s result(s)", len(documents))
            return documents
        except EmbeddingError as exc:
            raise VectorStoreError(f"Embedding failed: {exc}") from exc
        except Exception as exc:
            raise VectorStoreError(f"Similarity search failed: {exc}") from exc

    def get_statistics(self) -> Dict[str, Any]:
        """Return vector store statistics."""
        try:
            count = self._collection.count()
        except Exception as exc:
            raise VectorStoreError(f"Failed to get collection count: {exc}") from exc

        return {
            "collection_name": self.collection_name,
            "database_path": str(self.db_path),
            "document_count": count,
        }

    def reset_database(self) -> None:
        """Clear and recreate the ChromaDB collection."""
        try:
            self._client.delete_collection(self.collection_name)
        except Exception:
            logger.warning("Collection did not exist; creating a new one")

        self._collection = self._client.get_or_create_collection(name=self.collection_name)
        logger.info("Vector store collection reset")

    def _build_document_id(self, doc: Document, index: int) -> str:
        """Generate a stable ID for a document chunk."""
        return str(uuid.uuid4())
